teamterning/Terning-iOS

Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj, Terning-iOS/Terning-iOS/Resource/Extension/Foundation+/Date+.swift, Terning-iOS/Terning-iOS/Resource/UIComponents/CustomDatePicker.swift, Terning-iOS/Terning-iOS/Resource/Utils/getKrDate.swift
close #20 
<br/>
```swift
public extension Date {
func getCurrentKrYearAndMonth() -> (year: Int, month: Int) {
let currentDate = self
var calendar = Calendar.current
calendar.timeZone = TimeZone(identifier: "Asia/Seoul")!
let currentYear = calendar.component(.year, from: currentDate)
let currentMonth = calendar.component(.month, from: currentDate)
return (year: currentYear, month: currentMonth)
}
}
```
```swift
extension CustomDatePicker {
private func setSelectedRow() {
let (currentYear, currentMonth) = Date().getCurrentKrYearAndMonth()
if let initialYearIndex = years.firstIndex(of: currentYear),
let initialMonthIndex = months.firstIndex(of: currentMonth) {
self.selectRow(initialYearIndex, inComponent: 0, animated: false)
self.selectRow(initialMonthIndex, inComponent: 1, animated: false) …
```
=> [Feat] #20 - CustomDatePicker, getKrDate 구현했습니다. 

Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj, Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/ViewController+.swift, Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift, Terning-iOS/Terning-iOS/Resource/UIComponents/CustomButton.swift, Terning-iOS/Terning-iOS/Resource/UIComponents/CustomNavigationBar.swift, Terning-iOS/Terning-iOS/Resource/UIComponents/JobDetailInfoView.swift
close #14
<br/>
- CustomNavigationBar 구현
<br/>
- 아래처럼 프로퍼티 만들고, 레이아웃 평소처럼 똑같이 만들어 주면 됩니다.
생성자에 isShadow 프로퍼티를 사용해서 그림자를 없앨 수 있습니다.
```swift
private lazy var naviBar = CustomNavigationBar(self, type: .centerTitleWithLeftButton).setTitle("Shodow 있는 내비")
```
- 뒤로 가기 버튼을 누르면 자동으로 pop되는 코드를 심어놨고, `resetLeftButtonAction` 함수를 통해 커스텀 이벤트도 구현 할 수 있습니다.
<br/>
- 아래는 그림자 없는 버전 입니다 ~
<br/>
=> [Feat] #14 - Custom NavigatoinBar를 구현 했습니다.

Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj, Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_scrap.imageset/Contents.json, Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_scrap.imageset/Property 1=default.svg, Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_scrap.imageset/ios_ic_28_scrap.svg, Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_scrap_fill.imageset/Contents.json, Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_scrap_fill.imageset/Property 1=active.svg, Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_scrap_fill.imageset/Vector 1.svg, Terning-iOS/Terning-iOS/Resource/UIComponents/CustomScrapButton.swift, Terning-iOS/Terning-iOS/Resource/UIComponents/JobDetailInfoView.swift, Terning-iOS/Terning-iOS/Resource/UIComponents/JobSummaryInfoView.swift, Terning-iOS/Terning-iOS/Source/Data/Announcements/BottomInfoModel.swift, Terning-iOS/Terning-iOS/Source/Data/Announcements/CompanyInfoModel.swift, Terning-iOS/Terning-iOS/Source/Data/Announcements/DetailInfoModel.swift, Terning-iOS/Terning-iOS/Source/Data/Announcements/JobDetailModel.swift, Terning-iOS/Terning-iOS/Source/Data/Announcements/MainInfoModel.swift, Terning-iOS/Terning-iOS/Source/Data/Announcements/SummaryInfoModel.swift, Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/CompanyInfoTableViewCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/DetailInfoTableViewCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/JobDetailTableViewHeaderCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/MainInfoTableViewCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/SummaryInfoTableViewCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/View/JobDetailView.swift, Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewModel/JobDetailViewModel.swift
close #8 
<br/>
```swift
extension CustomScrapButton {
func updateImage() {
if self.isSelected {
self.setImage(selectedImage, for: .normal)
} else {
self.setImage(deselectedImage, for: .normal)
}
}
}
```
작업하면서 CustomScrapButton 컴포넌트를 추가로 제작해 놓았습니다.
```swift
func setScrapped(_ isScrap: Bool) {
scrapButton.isSelected = isScrap
scrapButton.updateImage()
}
```
다른 파일에서 해당 방식으로 위 컴포넌트를 사용할 수 있습니다. 
```swift
extension JobDetailView {
@objc private func goToUrl() {
guard let urlString = url, let url = URL(string: urlString) else { return }
UIApplication.shared.open(url, options: [:], completionHandler: nil)
}
}
```
지원 사이트로 이동하기 버튼의 경우 사파리로 해당 url을 이동하도록 해놓았습니다. 
<br/>
```swift
@frozen
enum JobDetailInfoType: Int, CaseIterable {
case mainInfo = 0
case companyInfo = 1
case summaryInfo = 2
case …
```
=> [Feat] #8 - 공고 상세 페이지 구현했습니다.

Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingView.swift, Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
close #37 
<br/>
버튼 클릭 후 다른 버튼을 클릭하면 전에 클릭되어 있던 버튼 외에 다른 버튼도 `isSelected`가 `false`가 되어서 `false`를 중복되게 하는 로직으로 구현했는데 이번 PR에서 이전에 선택된 버튼만 `isSelected`가 `false`가 되도록 수정하였습니다.
상단의 네비게이션 바를 구현하였습니다. 커스텀 네비게이션 바가 나중에 수정된다고 해서 레이아웃만 잡아보았고 백버튼은 구현하지 않았습니다.
UIButton+ extension을 이용해서 구현했고 일괄적으로 서버에 PUT 할 수 있게 정보를 한번에 출력되도록 했습니다. 
<br/>
```swift
@objc
func gradeButtonDidTap(_ sender: UIButton) -> UIButton {
var gradeButtons_dict: [UIButton: Int] {
return [
rootView.gradeButton1: 0,
rootView.gradeButton2: 1,
rootView.gradeButton3: 2,
rootView.gradeButton4: 3
]
}
for gradeButton in gradeButtons_dict {
if gradeButton.key  == sender {
gradeButton.key.backgroundColor = .terningMain
gradeButton.key.setTitleColor(.white, for: .normal)
gradeButton.key.isSelected.toggle()
grade = gradeButton.value …
```
=> [Feat] #37 - 필터링 세팅 뷰 선택된 버튼 일괄 전달 작업 완료했습니다.

Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj, Terning-iOS/Terning-iOS/Network/TargetType/ScrapsTargetType.swift, Terning-iOS/Terning-iOS/Resource/UIComponents/CustomSearchView.swift, Terning-iOS/Terning-iOS/Resource/UIComponents/CustomSortButton.swift, Terning-iOS/Terning-iOS/Source/Data/Home/JobCardModel.swift, Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/InavailableFilterView.swift, Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/JobCardScrapedCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/Home/MainHomeViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/Cell/GraphicCollectionViewCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/Cell/SortHeaderCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/View/SearchResultView.swift, Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift
close #73 
<br/>
기존에 만들어두신 `JobCardScrapedCell`, `InavailableFilterView`, `JobCardModel` 활용해서 구현했습니다! `JobCardModel`의 이미지 데이터를 UIImage에서 String으로 변경하였고 그에 맞게 bind도 변경해놓았습니다!
```swift
// MARK: - Methods
func bindData(model: JobCardModel) {
self.internshipAnnouncementId = model.internshipAnnouncementId
self.jobCardCoverImage.setImage(with: model.companyImage, placeholder: "placeholder_image")
self.daysRemaining.text = model.dDay
self.jobLabel.text = model.title
self.period.text = model.workingPeriod
self.scrapButton.isSelected = model.isScraped
}
```
현재 SortHeaderCell과 CustomSortButton은 UI만 만들어놓은 상태이고, 화면에 추가하거나 로직을 추가하지 않았습니다. 
<br/>
```swift
private let sortBySubject = BehaviorSubject<String>(value: "deadlineSoon")
private let pageSubject = BehaviorSubject<Int>(value: 0)
private var …
```
=> [Feat] #73 - 탐색 뷰 구현했습니다.

Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj, Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift, Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/FilterInfoCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/InavailableFilterView.swift, Terning-iOS/Terning-iOS/Source/Presentation/NewHome/GradientLayerView.swift, Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeView.swift, Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeViewController.swift
close #112 
<br/>
다양한 방법이 있었지만 어제 이야기를 해보면서 이 방향이 맞다고 판단하여 이렇게 구현하게 되었습니다. 
추가로 그라데이션이 있는 뷰도 따로 만들어서 스크롤 하다가 헤더가 붙으면 그라데이션 뷰가 뜨는 것까지 구현해주었습니다. 
이건 단순히 명진이 형이 구현해놓은 코드에 한줄만 추가해서 해결했습니닷
다음 이슈애서 구현할 정렬 기능을 위한 밑작업을 해줬습니다. 
notification center를 이용한 방법과 delegate를 이용한 방법 중 후자의 방법이 익숙해 사용했으나 이렇게 되면 뷰컨에 너무 강한 결합을 하는 친구들이 많아져서 혹시 약한 결합을 하는 것이 좋다고 생각된다면 전자의 방법도 사용해보겠습니다. 
+) 이 문제를 해결하다가 필터링 설정이 완료되었을 때 뜨는 토스트 메시지가 bottom sheet와 같이 사라지는 것을 발견했습니다. 이는 추후 수정하겠습니다.
<br/>
원래는 UIAdaptivePresentationControllerDelegate 구현한 것을 쓰려고 했는데 뭔가 계속 꼬여서 결국 `didSaveSetting()` 이라는 함수를 따로 만들었습니다. 함수안에서 중복되는 내용은 함수화 해주었습니댜.
```swift
// UIAdaptivePresentationControllerDelegate를 구현하여 바텀시트가 사라질 때 호출되는 메서드 추가
extension NewHomeViewController: UIAdaptivePresentationControllerDelegate {
func removeDimmedBackgroundView() {
if …
```
=> [Fix] #112 - sticky header를 구현했습니다.

Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/terning_sub3.colorset/Contents.json, Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift, Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/IsScrapInfoViewCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/NonScrapInfoCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/ScrapInfoHeaderCell.swift
close #131
<br/>
* UI컴포넌트를 추가하면서 바인딩해야하는 값들이 있어 그 부분과 관련해서 수정하였습니다.,
* 높이와 너비 정도 수정되었고 inset과 같은 값을 수정했습니다. 
* 추가적으로 이렇게 레이아웃을 잡을 경우 곧 마감되는 공고카드가 없을 때 뜨는 화면의 레이아웃이 잘 잡히지 않을 것 같아서 
분기처리를 통해서 이를 위한 레이아웃을 따로 잡아줘야하지 않을까 하는 생각입니다. 
* dDay 라벨의 배경이 되는 라운딩된 둥근 사각형의 색상이 컬러 에셋에 없어서 추가해주었습니다.
* 추가된 컬러의 이름은 terning_sub3입니다. 
|    내용    |   이미지  |
|:---------------:|:------------------:|
| 컬러 추가한 부분 | <img width="66" alt="스크린샷 2024-09-07 오후 2 40 41" src="https://github.com/user-attachments/assets/3a904fab-f8bb-40b2-b67b-12c9d6bfc6e8"> |
* 곧 마감되는 공고카드가 없을 때의 레이아웃 분기처리를 해주었습니다.
<br/>
* 서버에서 따로 기업의 이름을 보내주지 않는데 이 부분은 정규식을 사용해서 
공고 카드의 title 데이터에서 대괄호 안의 내용을 추출하도록 했습니다.
|    내용    |   이미지  |
|:---------------:|:------------------:|
| 기업 이름 들어가는 부분 | <img width="97" alt="스크린샷 2024-09-07 오후 …
=> [Fix] #131 - 곧 마감되는 공고카드의 디자인 및 api 명세서의 변경사항을 반영해주었습니다. 

Terning-iOS/Terning-iOS/Resource/UIComponents/CustomButton.swift, Terning-iOS/Terning-iOS/Resource/UIComponents/CustomDatePicker.swift, Terning-iOS/Terning-iOS/Resource/UIComponents/CustomOnboardingButton.swift, Terning-iOS/Terning-iOS/Resource/UIComponents/CustomProgressView.swift, Terning-iOS/Terning-iOS/Source/Presentation/Welcome/View/WelcomeView.swift
close #152 
<br/>
<br/>
```swift
// MARK: - Public Methods
extension CustomDatePicker {
public func setInitialDate(year: Int, month: Int) {
if let initialYearIndex = years.firstIndex(of: year),
let initialMonthIndex = months.firstIndex(of: month) {
self.selectRow(initialYearIndex, inComponent: 0, animated: false)
self.selectRow(initialMonthIndex, inComponent: 1, animated: false)
onDateSelected?(year, month)
}
}
}
```
CustomDatePicker 년도 범위 수정하면서 초기 선택 날짜 넣을 수 있는 코드 추가해놓았습니다!
```swift
datePicker.setInitialDate(year: 2011, month: 1)
```
이런식으로 사용하시면 됩니다!
필터링 정보 조회한 후에 필터링 재설정 화면에서 해당 정보를 넣어주셔서 사용하면 될 것같습니다!
____________________________________________________________________________
```swift
private func updateBackgroundColor() {
let buttonStateHandler: UIButton.ConfigurationUpdateHandler = …
```
=> [Fix] #152 - 온보딩 페이지 QA 반영했습니다. 

Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/InavailableFilterView.swift, Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/RecommendCollectionViewCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/SearchCollectionViewHeaderCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/Search/View/SearchView.swift, Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/Cell/GraphicCollectionViewCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/Cell/SortHeaderCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/View/SearchResultView.swift, Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift, Terning-iOS/Terning-iOS/Source/Presentation/SortSetting/SortSettingViewController.swift
close #125 
<br/>
아직 탐색 결과 API가 수정되지 않아서 DTO 수정과 스크랩 수정은 하지 않았습니다!
```swift
// TODO: totalPages를 totalCounts로 변경
let totalCounts = searchResponse
.map { $0.totalPages }
.asDriver(onErrorJustReturn: 0)
```
아직 반환값에 totalCounts 가 없어서 .totalPages값을 대충 넣어둔 상태라 검색 결과가 하나로 보입니다!
추후 API 수정이 완료되면 변경하겠습니다.
변경된 UI에서는 검색 전에 그래픽보이던게 사라졌는데, 
아직 완전히 없애는 건지 확실하지 않아서 `GraphicCollectionViewCell`는 그대로 두었고, 그래픽이미지만 빈 채로 두었습니다!
검색 결과 셀도 UI가 수정되었는데 `JobCardScrapedCell`을 다른 화면에도 사용하고 있길래, 일단 수정하지 않고 두었습니다!
<br/>
```swift
private static func createSearchSection(hasResults: Bool) -> NSCollectionLayoutSection {
let itemSize = NSCollectionLayoutSize(
widthDimension: .fractionalWidth(1.0),
heightDimension: .estimated(116)
)
let item = NSCollectionLayoutItem(layoutSize: itemSize)
let groupSize = …
```
=> [Fix] #125 - 탐색뷰 관련 UI 수정 반영했습니다. 

Terning-iOS/Terning-iOS/Resource/UIComponents/CustomSearchView.swift, Terning-iOS/Terning-iOS/Source/Data/Announcements/JobDetailModel.swift, Terning-iOS/Terning-iOS/Source/Data/Search/SearchResultModel.swift, Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/View/JobDetailView.swift, Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewModel/JobDetailViewModel.swift, Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/JobCardScrapedCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift
close #158 
<br/>
검색 결과에서 scrapId가 없어지고, 스크랩시 요청하는 색상이 색상 헥사코드에서, 약속한 string 값으로 변경됨에 따라 스크랩 버튼을 지금 누르면 오류가 발생하는 상태이긴 합니다!
스크랩 모델이 전체적으로 수정되야해서, 해당 오류는 해결하지 않았습니다!
<br/>
```swift
let totalCounts = searchResponse
.map { $0.totalCount }
.asDriver(onErrorJustReturn: 0)
```
totalPages를 임시로 넣어놨던 자리에 totalCount를 제대로 넣어줘서, 검색 결과 갯수 잘 출력됩니다!
```swift
if model.isScrapped == false {
let startDateComponents = parseStartDate(model.startYearMonth)
let dailyScrapModel = DailyScrapModel(
scrapId: model.internshipAnnouncementId,
title: model.title,
color: model.color ?? "#ED4E54",
internshipAnnouncementId: model.internshipAnnouncementId,
dDay: model.dDay,
workingPeriod: model.workingPeriod,
companyImage: model.companyImage,
startYear: startDateComponents.year,
startMonth: startDateComponents.month
)
let …
```
=> [Fix] #158 - 공고 상세, 검색 결과 DTO 수정 및 탐색뷰 QA 반영했습니다. 

Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewModel/ProfileViewModel.swift
close #174 
<br/>
1. authType 옵셔널로 처리되어, 애플로그인도 KAKAO로 들어간 문제 해결
2. 공고 상세 스와이프로 뒤로가기 안되는 문제 해결
3. 홈뷰 `jobDetailVC.hidesBottomBarWhenPushed = true` 추가
<br/>
1. authType 옵셔널로 처리되어, 애플로그인도 KAKAO로 들어간 문제 해결
ProfileViewModel 에서 항상 authType이 nil 이어서 , KAKAO 만 되는 문제를, authType을 직접 넣어주는 형식으로 수정하여 해결 했습니다.
```swift
authType: Config.authType
```
2. JobDetailVC 스와이프 제스처 추가
ViewDidLoad에 해당 코드를 추가해서 제스처로도 공고에서 뒤로 갈 수 있게 수정 하였습니다.
```Swift
navigationController?.interactivePopGestureRecognizer?.delegate = nil
```
3. jobDetailVC.hidesBottomBarWhenPushed = true 코드 추가해서 탭바를 없애주었습니다.
<br/>
| 홈 -> 상세 | 캘린더 -> 상세 |
| - | - |
| ![홈](https://github.com/user-attachments/assets/4089b806-f2ae-445e-a958-2f012050660f) | ![캘린더](https://github.com/user-attachments/assets/896f523f-8ebd-43d6-a591-e94c93cd0ec8) | …
=> [Fix] #174 -  로그인, 공고상세 스와이프, 탭바 가벼운 문제들을 해결 하였습니다.

Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
close #192 
<br/>
탐색 결과에서 공고 상세로 넘어간 후, 공고 상세 페이지에서 스크랩 관련 요청을 한 후, back 버튼을 통해 탐색 결과로 돌아올 경우 해당 결과가 적용이 안되는 문제 발생
=> 해결했습니다!
<br/>
```swift
override func viewWillAppear(_ animated: Bool) {
super.viewWillAppear(animated)
if !self.isMovingToParent {
if let currentKeyword =  rootView.searchView.textField.text,
!currentKeyword.trimmingCharacters(in: .whitespaces).isEmpty,
let currentPage = try? pageSubject.value() {
sortBySubject.onNext(currentKeyword)
pageSubject.onNext(currentPage)
}
}
}
```
뷰 컨트롤러가 처음 부모 컨트롤러로 추가될 때, 즉 push되거나 present 될 때가 아닐때, 즉 back버튼으로 다시 화면에 돌아왔을때만
텍스트 필드값과 현재 페이지, 정렬을 그대로 전달해서 searchTrigger가 작동할 수 있도록 합니다. 
```swift
output.searchResults
.drive(onNext: { [weak self] newSearchResults in
guard let self = self else { return } …
```
=> [Fix] #192 - 탐색뷰 스크랩 오류 수정했습니다.

Terning-iOS/Terning-iOS/Resource/UIComponents/CustomOnboardingButton.swift, Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/InavailableFilterView.swift, Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/View/OnboardingView.swift, Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/View/SearchResultView.swift
close #203 
<br/>
<br/>
```swift
private func optionSelected(_ sender: CustomOnboardingButton) {
if sender == selectedButton {
selectedButton?.deselectButton()
selectedButton = nil
updateOnboardingData(for: viewType, with: nil)
optionSelectedSubject.onNext(nil)
} else {
selectedButton?.deselectButton()
selectedButton = sender
sender.selectButton()
let stringValue: String?
switch viewType {
case .grade:
switch sender.index {
case 0: stringValue = "freshman"
case 1: stringValue = "sophomore"
case 2: stringValue = "junior"
case 3: stringValue = "senior"
default: stringValue = nil
}
case .workingPeriod:
switch sender.index {
case 0: stringValue = "short"
case 1: stringValue = "middle"
case 2: stringValue = "long"
default: stringValue = nil
}
case .graduationDate:
stringValue = nil
} …
```
=> [Fix] #203 - 온보딩 & 탐색 3차 QA 반영했습니다. 

Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift
close #196 
<br/>
기존처럼 아래로 스크롤될때만 페이지 증가하고, 페이지 변경 후 API 요청했을때 기존 검색결과에 새로운 검색 결과를 쌓는 형식으로 되돌려놓았습니다. 
<br/>
```swift
override func viewWillAppear(_ animated: Bool) {
super.viewWillAppear(animated)
if !self.isMovingToParent {
if let indexPath = selectedIndexPath {
reloadCollectionViewItems(at: indexPath)
}
}
}
```
```swift
private func reloadCollectionViewItems(at indexPath: IndexPath) {
let pageSize = 10
// 요청 페이지 찾기 ex) 지금 indexPath가 18이면 28/10 = 2, 2페이지를 요청
let pageIndex = indexPath.item / pageSize
// 실제 받아올 인덱스 찾기 
// ex) 지금 indexPath가 28인데, API 호출결과로는 10단위씩 전달되기 때문에 2페이지를 요청했을때 10개의 리스트중 8번째에 위치
// 따라서 28 % 10 = 8 -> 8번째 데이터 찾기
let itemIndexInPage = indexPath.item % pageSize
// API 호출을 통해 현재 페이지 데이터 호출
viewModel.fetchJobCards(keyword: textFieldKeyword ?? "", sortBy: sortByRelay.value, …
```
=> [Fix] #196 - 페이지 되돌아왔을때, 해당 인덱스값의 데이터만 reload되게 변경했습니다.

Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj, Terning-iOS/Terning-iOS/Info.plist, Terning-iOS/Terning-iOS/Resource/Utils/setImage.swift, Terning-iOS/Terning-iOS/Source/Data/Network/Service/AuthInterceptor.swift, Terning-iOS/Terning-iOS/Source/Data/Network/Service/Providers.swift, Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/AnnouncementsTargetType.swift, Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/CalendarTargetType.swift, Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/FiltersTargetType.swift, Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/HomeTargetType.swift, Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/MyPageTargetType.swift, Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/ScrapsTargetType.swift, Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/SearchTargetType.swift
close #168 
<br/>
- info 에 `Queried URL Schemes` 추가
- xcconfig 적용되게 프로젝트에 추가 했습니다. (debug, release) -> $(KAKAO_APP_KEY) 와 같이 사용가능!
-> PR 포인트 참고
(이 부분이 이해가 안되면 디코로 알려드릴게요)
- 통신 중간에 세팅을 해서, 세션(토큰)이 만료 됐을때 retry를 해서 토큰을 세팅 해준다고 생각 해주면 될 거 같아요!
스유 브랜치에서 넣어야 하는데 모르고 커밋을 해버려서..ㅎㅎ
그냥 이런게 있다~ 정도만 보시면 될 듯 !!
<br/>
1) 아래  `AuthInterceptor` 함수에서
```swift
final class AuthInterceptor: RequestInterceptor { ... }
```
2) 이렇게 헤더에 세팅 되게 했숨다
```swift
urlRequest.setValue("Bearer \(accessToken)", forHTTPHeaderField: "Authorization")
```
3) 만약에 `retry` 함수에서 에서 상태코드 401을 만나면
```swift
func retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void) {
print("retry 진입")
guard let response = request.task?.response as? HTTPURLResponse,
response.statusCode == 401, …
```
=> [Fix] #168 - 카카오 로그인에서 카카오 앱이 작동 안되는 문제를 해결 했습니다.

Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/PlanFiltering/ViewController/PlanFilteringViewController.swift
close #236 
<br/>
<br/>
`createButtonGroup` 함수 안에서 내부 버튼 생성시, 버튼 높이 지정 코드를 유지해 주었고, UIStackView 자체의 높이 지정을 없애주었습니다!
내부 버튼에 따라 저절로 높이가 지정되도록 해주었습니다. 
```swift
private func createButtonGroup(titles: [String], section: Int) -> UIStackView {
let stackView = UIStackView().then {
$0.axis = .horizontal
$0.spacing = 12
$0.distribution = .fillEqually
}
titles.enumerated().forEach { index, title in
let button = CustomOnboardingButton(
originalTitle: title,
selectedTitle: title,
cornerRadius: 10,
height: 36.adjustedH
)
button.tag = section * 10 + index
stackView.addArrangedSubview(button)
}
return stackView
}
```
```swift
gradeButtons.snp.makeConstraints {
$0.top.equalTo(gradeTitleLabel.snp.bottom).offset(12.adjustedH)
$0.horizontalEdges.equalToSuperview()
}
```
<br/> …
=> [Fix] #236  - 필터링뷰 레이아웃 경고 수정

Terning-iOS/Terning-iOS/Source/Domain/Model/Filter/Grade.swift, Terning-iOS/Terning-iOS/Source/Domain/Model/Filter/JobType.swift, Terning-iOS/Terning-iOS/Source/Domain/Model/Filter/WorkingPeriod.swift, Terning-iOS/Terning-iOS/Source/Domain/Model/Home/UserFilteringInfoModel.swift, Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringView/ViewController/FilteringViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
close #240 
<br/>
FilteringViewController를 열 때, data로 필터링 정보 전달받고, 
초기화시 UserFilteringData.shared에 해당 값 업데이트해서 사용하는 방식으로 수정했습니다. 
<br/>
```swift
var filterInfos: UserFilteringInfoModel = UserFilteringInfoModel(
grade: nil, // 기본값 설정
workingPeriod: nil, // 기본값 설정
startYear: nil, // 기본값 설정
startMonth: nil, // 기본값 설정
jobType: nil
)
```
```swift
extension HomeViewController: FilterButtonProtocol {
func filterButtonDidTap() {
let filterSettingVC = FilteringViewController(
viewModel: FilteringViewModel(
filtersRepository: FiltersRepository(
filtersService: FiltersService(
provider: Providers.filtersProvider
)
)
), data: filterInfos
)
```
기존의 `HomeViewController`에서 `FilteringSettingViewController`로 전달하던 data에 jobType 추가했습니다. 
```swift
init(viewModel: FilteringViewModel, data: …
```
=> [Fix] #240 - 필터링뷰 초기화 시 전달된 데이터 기반 UserFilteringData 업데이트 방식으로 수정했습니다. 

Terning-iOS/Terning-iOS/Resource/UIComponents/CustomDatePicker.swift, Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/Cell/SortHeaderCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/Welcome/View/WelcomeView.swift
close #245 
<br/>
**온보딩**
= 필터링뷰 데이트피커 연도 범위 조정과 동일
**탐색뷰**
<br/>
skipButton 바텀과 슈퍼뷰 간의 간격 수정해주었습니다. 
+ 52 -> 44로 변경
+ 버튼 높이 설정 해줌
```swift
skipButton.snp.makeConstraints {
$0.height.equalTo(14.adjustedH)
$0.centerX.equalToSuperview()
$0.bottom.equalToSuperview().inset(44.adjustedH)
}
```
데이트 피커 초기 년도를 2022 ~ 올해, 현재 달이 10월 이상일 경우 2022 ~ 올해 + 1로 설정되도록 하였습니다. 
```swift
private(set) var years: [String] = {
let (currentYear, currentMonth) = Date().getCurrentKrYearAndMonth()
let endYear = currentMonth > 10 ? currentYear + 1 : currentYear
return Array(2022...endYear).map { "\($0)" }
}()
```
총 n개의 공고가 있어요. 에서 n개에 볼드처리 문제는 n 폰트를 -> body3에서 body5로 변경했습니다. 
```swift
let range = (fullText as NSString).range(of: countString)
attributedText.addAttributes([
.font: UIFont.body5,
.foregroundColor: …
```
=> [Fix] #245 - 온보딩 & 탐색뷰 3차 스프린트 QA 반영했습니다. 

Terning-iOS/Terning-iOS/Resource/Amplitude/AmplitudeEventType.swift, Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift, Terning-iOS/Terning-iOS/Resource/UIComponents/CustomButton.swift, Terning-iOS/Terning-iOS/Source/Data/Network/Service/Login/LoginService.swift, Terning-iOS/Terning-iOS/Source/Data/Network/User/UserManager.swift, Terning-iOS/Terning-iOS/Source/Domain/Model/Announcements/JobDetailModel.swift, Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/View/JobDetailView.swift, Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/MyPage/ViewModel/MyPageViewModel.swift, Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/Cell/StickyHeaderCell.swift, Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/MainSortButton.swift, Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/NewHomeViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/SortSetting/SortSettingViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarItem.swift
close #247
<br/>
(크리티컬한 작업 들만 적어둘게요! 간단한 문제들은 커밋 메세지 참고)
-> 기존 rx 를 활용하여, 페이징과 스티키헤더그림자 를 동시에 구현 했었는데, throttle로 인해 스티키헤더그림자가 off되는데 지연되는 바람에 발생한 문제 였습니다.
문제를 해결하기 위해 페이징과 스티키헤더 그림자 부분을 분리 해주었습니다.
```swift
rootView.collectionView.rx.contentOffset // 페이징 코드
.throttle(.milliseconds(500), scheduler: MainScheduler.instance)
.subscribe(onNext: { [weak self] offset in
guard let self = self else { return }
self.handlePagination(offset: offset)
self.isLoading = false
})
.disposed(by: disposeBag)
rootView.collectionView.rx.contentOffset // 그림자 온 오프 코드 따로 분리
.observe(on: MainScheduler.instance)
.subscribe(onNext: { [weak self] offset in
guard let self = self else { return }
if offset.y > 200 {
self.rootView.gradientLayerView.isHidden = false
} else {
self.rootView.gradientLayerView.isHidden = true …
```
=> [Fix] #247 - 3차 스프린트 1차 QA 반영 했습니다.

Terning-iOS/Terning-iOS/Resource/UIComponents/CustomSegmentedControl.swift, Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringView/ViewController/FilteringViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/JobFiltering/ViewController/JobFilteringViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/JobFiltering/ViewModel/JobFilteringViewModel.swift, Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/PlanFiltering/ViewController/PlanFilteringViewController.swift, Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/PlanFiltering/ViewModel/PlanFilteringViewModel.swift, Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/NewHomeViewController.swift
close #249 
<br/>
<br/>
```swift
private let selectedJobTypeRelay = BehaviorRelay<JobType?>(value: UserFilteringData.shared.jobType ?? JobType.allCases.last)
```
저장된 직무 필터값 없을때 마지막 값인 `전체`가 뜨게했습니다. 
```swift
func transform(input: Input, disposeBag: DisposeBag) -> Output {
input.jobSelected
.subscribe(onNext: { [weak self] indexPath in
guard let self = self else { return }
let selectedJob = JobType.allCases[indexPath.item]
self.selectedJobTypeRelay.accept(selectedJob)
})
.disposed(by: disposeBag)
```
```swift
output.selectedJobType
.drive(onNext: { [weak self] selectedJob in
guard let self = self, let selectedJob = selectedJob,
let index = JobType.allCases.firstIndex(of: selectedJob) else { return }
let indexPath = IndexPath(item: index, section: 0)
self.collectionView.selectItem(at: …
```
=> [Fix] #249 -필터링 재설정화면 3차 스프린트 1차 QA 반영했습니다.

Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj, Terning-iOS/Terning-iOS/Info.plist, Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/StickyHeaderCell.swift
close #252
<br/>
- 홈 화면에서, 공고가 1000개가 넘어 갈시 999+ 로 변경되게 수정 했어요 !
- 앱스토어 1.1.1 버전으로 업데이트 했어요 !
<br/>
- `StickyHeaderCell`
```swift
func bind(totalCount: Int, name: String) {
{ code }
totalCountLabel.text = totalCount >= 999 ? "999+" : "\(totalCount)"
}
```
<br/>
<br/>
=> [Fix] #252 - 홈 화면 개수가 1000개가 넘어갈 시 문구 변경 | v1.1.1 버전 업데이트

.gitignore, Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj, Terning-iOS/Terning-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved, Terning-iOS/Terning-iOS/Application/AppDelegate.swift, Terning-iOS/Terning-iOS/Info.plist, Terning-iOS/Terning-iOS/Terning-iOS.entitlements
close #261
<br/>
- 푸시알림 테스트 구현 (서버 연결 X)
<br/>
- AppDelegate 에 기능 주석 달아놨습니다.
아직 서버 연동까진 하지 않고, 테스트만 했습니다. 서버 연동이 된다면 일부 코드가 수정 될 예정 입니다.
<br/>
<br/>
https://firebase.google.com/docs/cloud-messaging/ios/first-message?hl=ko&authuser=0&_gl=1*1xdyvuf*_up*MQ..*_ga*MjIyMDI4MjY4LjE3NDA5MzI1NjI.*_ga_CW55HF8NVT*MTc0MTE0NzI4OS40LjEuMTc0MTE0Nzc3OS41NC4wLjA.
<br/>
=> [Feat] #261 - firebase Push Notification 을 구현 했습니다.

Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj, Terning-iOS/Terning-iOS/Data/Network/Services/AnnouncementsService.swift, Terning-iOS/Terning-iOS/Data/Network/Services/MypageService.swift, Terning-iOS/Terning-iOS/Data/Network/Services/SearchService.swift
close #271 
<br/>
서비스 레이어 추가했습니다.
- SearchService(API 3개)
- MypageService(API 2개)
- AnnouncementsService(API 1개)
<br/>
각각의 ServiceProtocol의 func의 파라미터와 반환값은 기존에 있던 API 호출 코드 그대로 반영해서 작성했습니다!
Service안의 func은 전부 API 호출한 후 응답 DTO 변환하여 반환하는 모습으로 작성되었습니다. 
서비스는 호출만 하는 역할이라고 생각해서, 딱히 다른 코드를 추가하지 않았는데 더 필요한게 있을까요?
Service안의 func 이름들은 전부 TargetType의 case이름과 통일 시켰습니다. 공고 상세 조회하기의 경우에만  TargetType의 case이름이 getAnnouncements이길래, 다른 공고 조회 API과 헷갈릴 것 같아서 getDetailAnnouncements로 바꿔서 작성했습니다.
예시) 기존 코드
```swift
extension SearchResultViewModel {
func fetchJobCards(keyword: String, sortBy: String, page: Int, size: Int) -> Observable<SearchResultModel> {
return Observable.create { observer in
let request = self.searchProvider.request(
.getSearchResult(
keyword: keyword,
sortBy: sortBy,
page: page,
size: size …
```
=> [Feat] #271 - 서비스 레이어 추가했습니다.

Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj, Terning-iOS/Terning-iOS/Presentation/Splash/SplashViewController.swift
close #288 
<br/>
강제 업데이트 구현했습니다.
질문 세개 있습니다!
Remote Config에서 캐시된 값 갱신 주기를 24시간으로 설정해두었는데, 적절할까요?
```swift
settings.minimumFetchInterval = 86400
```
Remote Config에 android를 iOS로 바꿔서 매개변수 만들어주시면 감사하겠습니다!
해당 부분은 매개변수 새로 생기면 이름 수정하고, 주석 없애고 commit 추가하겠습니다
여기서 매개변수 이름을 근데 숨기는게 더 좋나요?
```swift
let remoteVersion = remoteConfig.configValue(forKey: "android_app_version").stringValue
//            let remoteVersion = "1.1.6"
let majorTitle = remoteConfig.configValue(forKey: "android_major_update_title").stringValue
let majorBody = remoteConfig.configValue(forKey: "android_major_update_body").stringValue
let patchTitle = remoteConfig.configValue(forKey: "android_patch_update_title").stringValue
let patchBody = remoteConfig.configValue(forKey: "android_patch_update_body").stringValue
let …
```
=> [Feat] #288 - 강제 업데이트 구현했습니다.

Terning-iOS/Terning-iOS/Presentation/Splash/SplashViewController.swift, Terning-iOS/Terning-iOS/Resource/UIComponents/CustomOnboardingButton.swift
close #292 
<br/>
isWaitingForForceUpdate관련 코드 제거
<br/>
isWaitingForForceUpdate는 업데이트 팝업에서 [업데이트하기] 버튼을 눌렀을 때,
앱스토어로 이동한 후 앱에 돌아왔을 때 다시 팝업을 띄우기 위한 일시적인 상태 플래그로 사용했습니다.
그러나 앱을 완전히 종료한 후 재실행할 경우, isWaitingForForceUpdate는 더 이상 유효하지 않아서 다시 팝업이 뜨지 않는 문제가 있었고
앱 복귀 시 무조건 다시 업데이트 여부 체크를하면 isWaitingForForceUpdate 플래그 없이도, 앱스토어로 이동한 후 앱에 돌아왔을 때 다시 팝업 을 띄울 수 있어서, 생각해보니 필요 없는 코드라 생각해서 삭제했습니다!
<br/>
강제 업데이트
https://github.com/user-attachments/assets/0de845aa-0e03-4747-a5da-5012ddfa9328
선택 업데이트
https://github.com/user-attachments/assets/207714bd-188e-4190-8a03-4de5675cba90
<br/>
=> [Fix] #292 - 업데이트 팝업 로직 수정했습니다.

Terning-iOS/Terning-iOS/Application/SceneDelegate.swift, Terning-iOS/Terning-iOS/Presentation/JobDetail/ViewModel/JobDetailViewModel.swift
close #295 
<br/>
Android Scheme과 iOS Scheme을 통일시키면서 사용자 인자 값 이름들이 변경되었습니다!
<br/>
딥링크 처리 
```swift
private func handleDeeplink(_ url: URL) {
guard let components = URLComponents(url: url, resolvingAgainstBaseURL: false),
let redirect = components.queryItems?.first(where: { $0.name == "redirect" })?.value,
let id = components.queryItems?.first(where: { $0.name == "internId" })?.value,
redirect == "intern" else {
return
}
```
인자 이름 변경
```swift
let templateArgs: [String: String] = [
"COMPANY_IMG": job.companyImage,
"TITLE": job.title,
"DEADLINE": job.deadline,
"PERIOD": job.workingPeriod,
"START_DATE": job.startYearMonth,
"redirect": "intern",
"internId": "\(input.internshipAnnouncementId.value)"
]
```
<br/>
https://github.com/user-attachments/assets/9cff6af1-cbec-44d4-9ace-4073acee2303 …
=> [Fix] #295 - 카카오톡 공유하기 사용자 인자 값 수정했습니다.

README.md, Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj, Terning-iOS/Terning-iOS/Application/SceneDelegate.swift, Terning-iOS/Terning-iOS/Data/Network/User/UserManager.swift, Terning-iOS/Terning-iOS/Presentation/Login/ViwController/LoginViewController.swift
close #307
<br/>
1. 로그인 과부하 걸리는 경우가 있다하여 (안드 / 아요) 로그인 로직 일부 수정 했습니다.
2. 앱스토어 1.6.0 버전 배포 했습니다.
<br/>
429번 을 받으면, 전역적으로 로그인 버튼을 10초 정도 비활성화 하게 했습니다.
```swift
} else if status == 429 {
print("🚫 429 Too Many Requests")
NotificationCenter.default.post(name: .didReceiveRateLimit, object: nil)
completion(.failure(.networkFail))
private func observeRateLimit() {
NotificationCenter.default.addObserver(
forName: .didReceiveRateLimit,
object: nil,
queue: .main
) { [weak self] _ in
self?.loginView.kakaoLoginButton.isEnabled = false
self?.loginView.appleLoginButton.isEnabled = false
self?.showToast(message: "요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.")
DispatchQueue.main.asyncAfter(deadline: .now() + 10) {
self?.loginView.kakaoLoginButton.isEnabled = true
self?.loginView.appleLoginButton.isEnabled = true
}
}
} …
```
=> [Fix] #307 - 로그인 로직 서버 요청에 따라 수정 했습니다.
