teamterning/Terning-iOS

- README.md
close #4 
<br/>
- 서비스 내용 추가
- 라이브러리 추가
- PR 룰 추가
- 개발 환경, 라이브러리 내역 추가
> [Docs] #4 - README 수정

- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Resource/UIComponents/CustomProgressView.swift
close #12 
<br/>
```swift
circleView.layer.borderColor = index < currentStep ? UIColor.calRed.cgColor : UIColor.grey200.cgColor
```
calRed색깔 Assets 추가한 후 나중에 변경 필요합니다~~ ( #52C689컬러로 교체 필요)
<br/>
```swift
private let progressView = CustomProgressView(currentStep: 3, totalSteps: 3, circleSize: 28, lineLength: 12)
```
해당 코드처럼 사용하시면 됩니다. 
totalSteps만큼 동그라미를 생성하고 totalSteps-1만큼 선을 생성합니다. 
```swift
func setStep(currentStep: Int) {
for (index, circleView) in circleViews.enumerated() {
circleView.backgroundColor = index < currentStep ? .terningMain : .grey300
circleView.layer.borderColor = index < currentStep ? UIColor.calRed.cgColor : UIColor.grey200.cgColor
}
for (index, lineView) in lineViews.enumerated() {
lineView.backgroundColor = index < currentStep - 1 ? .terningMain : .grey400
}
}
``` …
> [Feat] #12 -  progress 컴포넌트 구현했습니다.

- Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
close #44 
<br/>
변경된 커스텀 네비 바를 적용하였습니다.
<br/>
```swift
lazy var navi = CustomNavigationBar(type: .centerTitleWithLeftButton, isShadow: true).setTitle("필터링 재설정")
```
<br/>
<br/>
<br/>
> [Fix] #44 - 변경된 커스텀 네비 바 적용하였습니다.

- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/FilterHeaderCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/NonJobCardHeaderCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/ScrapInfoHeaderCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/IsScrapInfoViewCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/NonScrapInfoCells.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/MainHomeView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/MainHomeViewController.swift
close #54
<br/>
깃 충돌 해결 
<br/>
> [Hotfix] #54 - 깃 충돌 해결 했습니다.

- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Application/SceneDelegate.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Login/ViewModel/LoginViewModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Login/ViwController/LoginViewController.swift
- Terning-iOS/Terning-iOS/Terning-iOS.entitlements
close #53 
<br/>
애플 로그인 구현 완료!
<br/>
<br/>
https://github.com/user-attachments/assets/b74c01c4-c5b7-4263-8366-fe190984217d
> [Feat] #53 - Apple Login 구현 했습니다.

- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Application/AppDelegate.swift
- Terning-iOS/Terning-iOS/Application/SceneDelegate.swift
- Terning-iOS/Terning-iOS/Info.plist
- Terning-iOS/Terning-iOS/Network/TargetType/AuthTargetType.swift
- Terning-iOS/Terning-iOS/Network/TargetType/ScrapsTargetType.swift
- Terning-iOS/Terning-iOS/Network/User/UserManager.swift
- Terning-iOS/Terning-iOS/Source/Data/Home/JobCardModel.swift
- Terning-iOS/Terning-iOS/Source/Data/SignIn/SignInResponseModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/JobCardScrapedCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/MainHomeViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Login/ViewModel/LoginViewModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Login/ViwController/LoginViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Profile/View/ProfileView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewController/ProfileViewController.swift
close #62
<br/>
https://github.com/user-attachments/assets/3d8a53ae-c21a-40f9-a76a-5aa1cc59630e
> [Fix] #62 - 스크랩 기능 구현, 카카오 로그인 구현

- Terning-iOS/Terning-iOS/Info.plist
- Terning-iOS/Terning-iOS/Network/TargetType/AuthTargetType.swift
- Terning-iOS/Terning-iOS/Network/TargetType/CalendarTargetType.swift
- Terning-iOS/Terning-iOS/Network/User/UserManager.swift
- Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/ViewController+.swift
- Terning-iOS/Terning-iOS/Source/Data/SignIn/NewTokenModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Login/ViewModel/LoginViewModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Splash/SplashViewController.swift
close #71
<br/>
- 자동 로그인 관련 서버 API 가 변경되어서 model을 수정 했습니다.
- 캘린더 API 연결은 헀는데, 데이터가 없어서 테스트를 못했습니다 ㅠ.ㅠ
<br/>
자동 로그인은 아래처럼 accessToken도 업데이트 해주는 코드를 추가했습니다.
```swift
self.accessToken = data.accessToken
self.refreshToken = data.refreshToken
```
<br/>
> [Feat] #71 - 자동 로그인 수정, 캘린더 API 연결

- Terning-iOS/Terning-iOS/Source/Data/Search/AdvertisementsModel.swift
- Terning-iOS/Terning-iOS/Source/Data/Search/RecommendAnnouncementModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/AdvertisementCollectionViewCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/RecommendCollectionViewCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/View/SearchView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewModel/SearchViewModel.swift
close #77 
<br/>
작업한 내용은 위와 같습니다! 그 외에도 네비게이션 연결, Layout 조절 등 세부적 사항 수정했습니다!
```swift
import UIKit
// MARK: - AdvertisementsModel
struct AdvertisementsModel {
let advertisements: [UIImage]?
}
```
광고 API 모델
```swift
import Foundation
// MARK: - RecommendAnnouncementModel
struct RecommendAnnouncementModel: Codable {
let announcements: [RecommendAnnouncement]?
}
struct RecommendAnnouncement: Codable {
let internshipAnnouncementId: Int
let companyImage: String
let title: String
}
```
추천 공고 API 모델 입니다. 
이전과 타입이나 이름이 변경되었습니다. 자세히 봐주시길 바랍니다!
<br/>
```swift
var headers: [String: String]? {
return Config.testRefreshToken
}
```
기존 코드는 "accessToken": Config.accessToken"으로 요청이 되서 400 에러가 납니다.
"Authorization": "Bearer ${인증토큰}"으로 confige파일 수정해서 테스트 했습니다!  
수정시 다른 파일에서 에러나 충돌이 생길 것 같아서 일단, 변경 사항 무시하고 …
> [Feat] #77 - 탐색 뷰 API 연결했습니다. 

- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Source/Data/Search/SearchResultModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/JobCardScrapedCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/View/SearchResultView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift
close #79 
<br/>
<br/>
```swift
example Code
```
<br/>
https://github.com/user-attachments/assets/d03abf9c-a65d-43d6-b441-7a93f76ad122
<br/>
<br/>
> [Feat] #79 - 탐색 결과 뷰 API 연결했습니다.

- Terning-iOS/.swiftlint.yml
- Terning-iOS/Terning-iOS/Application/SceneDelegate.swift
- Terning-iOS/Terning-iOS/Network/TargetType/CalendarTargetType.swift
- Terning-iOS/Terning-iOS/Source/Data/Calendar/ScrapModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/JobListingCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/TNCalendarDateCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewController/ProfileViewController.swift
close #81
<br/>
- Calendar 서버 연결을 하였습니다.
DTO를 잘 만들어서 서버통신을 원활하게 진행하였습니다.
캘린더 버튼 이
<br/>
```swift
func calendar(_ calendar: FSCalendar, didSelect date: Date, at monthPosition: FSCalendarMonthPosition) {
if selectedDate == date {
calendar.setScope(.month, animated: true)
selectedDate = nil
} else {
selectedDate = date
calendar.setScope(.week, animated: true)
updateBottomCollectionViewHeader(for: date) // 선택된 날짜로 헤더 업데이트
fetchDailyData(for: date)
}
calendar.reloadData()
}
```
1. 전체 캘린더
2. 주간 캘린더
3. 전체 리스트 뷰 캘린더
<br/>
https://github.com/user-attachments/assets/d449ce0a-1aa8-49f5-ad43-094e59b4731c
<br/>
> [Feat] #81 - 캘린더 API 연결 하였습니다.

- Terning-iOS/Terning-iOS/Network/TargetType/AnnouncementsTargetType.swift
- Terning-iOS/Terning-iOS/Source/Data/Announcements/JobDetailModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/CompanyInfoTableViewCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/View/JobDetailView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewModel/JobDetailViewModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
close #82 
<br/>
<br/>
```swift
example Code
```
<br/>
https://github.com/user-attachments/assets/b137cd79-1545-40fb-95e0-9091da2b2fc6
<br/>
<br/>
> [Feat] #82 - 공고 상세 페이지 조회 API 연결

- Terning-iOS/Terning-iOS/Network/TargetType/HomeTargetType.swift
- Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift
- Terning-iOS/Terning-iOS/Source/Data/Home/JobCardModel.swift
- Terning-iOS/Terning-iOS/Source/Data/Home/ScrapedAndDeadlineModel.swift
- Terning-iOS/Terning-iOS/Source/Data/Home/UserFilteringInfoModel.swift
- Terning-iOS/Terning-iOS/Source/Data/Home/UserProfileInfoModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/FilterHeaderCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/IsScrapInfoViewCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/MainHomeViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/MyPage/MyPageViewController.swift
close #89
<br/>
- 캘린더 제거 기능을 구현 하였습니다.
<br/>
```swift
private func cancelScrapAnnouncement(internshipAnnouncementId: Int, cell: JobCardScrapedCell) {
providers.request(.removeScrap(scrapId: internshipAnnouncementId)) { [weak self] result in
LoadingIndicator.hideLoading()
guard let self = self else { return }
switch result {
case .success(let response):
let status = response.statusCode
if 200..<300 ~= status {
print("스크랩 취소 성공")
cell.updateScrapButton(isSelected: false)
} else {
print("400 error")
self.showToast(message: "네트워크 오류")
}
case .failure(let error):
print(error.localizedDescription)
self.showToast(message: "네트워크 오류")
}
}
}
```
<br/>
https://github.com/user-attachments/assets/a36482e3-b148-48f2-9cd3-60a35590dd83
<br/>
<br/>
> [Feat] #72 - 홈화면 API 연결중입니다.

- Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/ViewController+.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/JobListingCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
close #88 
<br/>
<br/>
```swift
```
<br/>
<br/>
<br/>
> [Feat] #88 - 스크랩 삭제 구현

- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Resource/UIComponents/CustomScrapButton.swift
- Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewModel/JobDetailViewModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Login/ViewModel/LoginViewModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Logout/LogoutViewContoller.swift
- Terning-iOS/Terning-iOS/Source/Presentation/MyPage/MyPageViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/ScrapInfoHeaderCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/View/OnboardingView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/ViewController/OnboardingPageViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
close #97 
<br/>
1. 최소 배포 버전 `16.0` 으로 변경 , (기존 15.0)
2. 필터링 재설정 모달 방식으로 변경
3. 컨벤션 Lint 수정 ( +코드 약간 정리 )
<br/>
커스텀 으로 만든 바텀시트가 아닌, `detents` 를 활용한 방식으로 구현 했습니다.
레이아웃은 피그마 보고 다시 짰습니다.
```swift
extension NewHomeViewController: FilterButtonProtocol {
func filterButtonDidTap() {
let filterSettingVC = FilteringSettingViewController(data: filterInfos)
let fraction = UISheetPresentationController.Detent.custom { _ in self.view.frame.height * (658/812) }
if let sheet = filterSettingVC.sheetPresentationController {
sheet.detents = [fraction, .large()]
sheet.largestUndimmedDetentIdentifier = nil
filterSettingVC.modalPresentationStyle = .overFullScreen
}
self.present(filterSettingVC, animated: true)
}
}
```
<br/>
|  iPhone 13 mini | iPhone 15 Pro   |
|---|---|
|  ![Simulator Screen Recording - …
> [Fix] #97 - 필터링 재설정 방식을 BottomSheet 모달 방식으로 구현 했습니다.

- Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/CALayer+.swift
- Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift
- Terning-iOS/Terning-iOS/Resource/UIComponents/CustomNavigationBar.swift
- Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/CalendarDateHeaderView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/TNCalendarDateCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/View/TNCalendarView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeView.swift
close #109 
<br/>
1. 캘린더 레이아웃 피그마에 맞게 변경
<br/>
앱잼 때, 레이아웃을 동일하게 맞추지 못했는데, 그 부분들만 개선했습니다.
전체 구조도 리팩터링 하려했는데, 릴리즈 이후로 미룰게요!
<br/>
<br/>
> [Fix] #109 - Calendar 일부 레이아웃 변경

- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/TNCalendarDateCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/View/CalendarDateCellView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
close #120 
<br/>
1. 주간 캘린더 일때 **띠지를 안보이게 하는 기능 ** 으로 변경
2. 주간 캘린더에서 월간 캘린더로 **스와이프**해서 넘어가는 기능 추가
<br/>
-  ## 띠지 Hidden 기능
`CalendarDateCellView` 는 저희 달력에, 하나하나 보이는 뷰 입니다. 1일, 2일, 3일 ... 30일, 31일 이렇게 따로따로
캘린더 Cell위에 올라가는 뷰인데 그 안에 새로운 함수를 추가했습니다.
`setViewMode` 가 `true` 이면 히든 처리하고
`false` 이면 다시 보이게 합니다.
```
func setViewMode(isWeekView: Bool) {
eventStackView.isHidden = isWeekView
}
```
`FSCalendar`의 크기가 변경될때 호출되는 델리게이트 메서드 `boundingRectWillChange` 안에서 띠지를 숨기거나, 보여주게 하는 기능을 추가해줍니다.
여기에 아래와 같은 코드를 작성해줍니다.
```
let isWeekView = calendar.scope == .week
if let visibleCells = calendar.visibleCells() as? [TNCalendarDateCell] {
for cell in visibleCells {
cell.cellView.setViewMode(isWeekView: isWeekView)
}
}
```
`calendar.visibleCells()` 를 하면 현재 FSCalendar에 등록되어있는 모든 Cell 을 받아오고, 각각 접근하여 숨김 처리를 …
> [Fix] #120 - 캘린더 일부 기능을 수정 하였습니다.

- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/FilterInfoCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/SortSetting/SortSettingView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/SortSetting/SortSettingViewController.swift
close #114 
<br/>
* 원래 단순하게 구현을 하려고 했지만 최대한 배운거 써먹으려고 enum을 할용해서 효율적으로 만들어보았습니다.
* 정렬 옵션을 받아야 하기 때문에 파라미터를 추가해줬구요 파라미터에 따른 분기처리를 해서 네트워크 path parameter에 넣어주었습니다.
* 원래 `selectedOption`의 값을 미리 설정해서 이를 해결하려고 했으나 뭔가 잘 안되더라구요..??(그렇게 하려면 진짜 대규모 공사...)
* 따라서 `UserDefault`를 이용해서 바텀시트에서 유저가 선택한 것을 저장해놓는 것으로 해결했습니다. 
다만 이 과정에서 앱을 재실행할 경우 `UserDefault`가 메모리에 영구적으로 남아있어 HomeVC에서 
`viewDidLoad` 상태에서 `UserDefault`가 채용마감 이른 순(`deadlineSoon`)으로 초기화되도록 했습니다.
<br/>
```swift
enum SortingOptions: String, CaseIterable {
case earlyDeadLine = "채용 마감 이른순" // api 명세서에 맞게 수정
case shortTerm = "짧은 근무 기간 순"
case longTerm = "긴 근무 기간 순"
case scraps = "스크랩 많은 순"
case views = "조회수 많은 순"
var title: String {
return self.rawValue // default
}
var defaultColor: UIColor {
return .grey400
}
var selectedColor: UIColor {
return …
```
> [Feat] #114 - 정렬기능 구현

- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Network/Service/Login/LoginService.swift
- Terning-iOS/Terning-iOS/Network/TargetType/AuthTargetType.swift
- Terning-iOS/Terning-iOS/Network/TargetType/MyPageTargetType.swift
- Terning-iOS/Terning-iOS/Network/User/UserManager.swift
- Terning-iOS/Terning-iOS/Source/Data/SignIn/NewTokenModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Login/ViewModel/LoginViewModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Login/ViwController/LoginViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Splash/SplashViewController.swift
- Terning-iOS/Terning-iOS/Source/Repository/LoginRepository.swift
close #119 
<br/>
```
1. 서비스 레이어 분리
2. 레포지토리 레이어 분리
3. 그에 따른 뷰모델 간소화
4. 로그인 관련 API 수정
```
<br/>
서비스 레이어는 주로 비즈니스 로직을 처리하는 계층 입니다.
지금 수정된 코드에는 서버 API 를 통신 하는 작업과, 로그인 로직이 진행됩니다.
```swift
protocol LoginServiceProtocol {
func loginWithKakao() -> Observable<Bool>
func loginWithApple() -> Observable<Bool>
}
```
레포지토리는 데이터 접근 및 조작을 담당하는 계층입니다.
지금은 API 밖에 가져오는 로직밖에 없지만, 필요시 DB, FileManager를 통해 더 많은 데이터에 접근할 수 있는 레이어입니다.
```swift
protocol LoginRepositoryProtocol {
func loginWithKakao() -> Observable<Bool>
func loginWithApple() -> Observable<Bool>
}
```
레포지토리를 생성자로 주입 받아서, 사용 합니다.
```swift
private let loginRepository: LoginRepositoryProtocol
init(loginRepository: LoginRepositoryProtocol) {
self.loginRepository = loginRepository
}
```
외부 에서는 아래 처럼 생성 합니다.
```swift
private func pushToSignInView() { …
```
> [Refactor] #119 - 소셜 로그인 MVVM 구조로 전면 수정 했습니다.

- Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/SortSetting/SortSettingViewController.swift
close #123 
<br/>
기존의 커스텀 픽커뷰를 사용하면서 또 델리게이트를 하여 픽커뷰를 구현했던 것이 문제였습니다. 
그래서 아마 기존의 것을 덮어썼기 때문에 레이아웃이 민지 누나가 구현한데로 나오지 않았던 것 같습니다.
코드를 삭제한게 끝이라 따로 코드를 올리진 않겠습니다.
* 그리고 이걸 고치고 나니 필터링에서 날짜가 전달이 안되는 것 같더군요
그래서 이 문제는 서버에서 변경한 사항 반영하면서 고치는게 좋을 것 같아 다음 이슈에서 해결하고자 합니다
* 브랜치 번호를 오해해서 #119로 커밋을 했습니다... 담부턴 꼼꼼히 보겠습니다. 참고바랍니닷
<br/>
|    구현 내용    |   iPhone 15 Pro   |
|:---------------:|:------------------:|
| 스크린샷            | <img src="https://github.com/user-attachments/assets/39b94633-ec01-4361-beea-bbe7aec400d6" width="250"> |
> [Fix] #123 - 픽커뷰 레이아웃을 디자인 명세서에 맞게 수정했습니다. 

- Terning-iOS/Terning-iOS/Resource/UIComponents/CustomButton.swift
close #137 
<br/>
- Custom 버튼이 기존에는 `able`/ `disable` 기능밖에 없었기 때문에, 따로 초기 배경색을 지정할 로직을 구현 안 했습니다.
활성화되어 있으면 기본적으로 terningMain 색으로 되어 있을 텐데, 이제 이 부분을 `setColor`로 변경할 수 있습니다.
<br/>
setColor 함수안에 있는 추가된 코드 입니다.
```swift
let buttonStateHandler: UIButton.ConfigurationUpdateHandler = { button in
var updatedConfiguration = button.configuration
switch button.state {
case .normal:
updatedConfiguration?.background.backgroundColor = bgColor
case .disabled:
updatedConfiguration?.background.backgroundColor = disableColor
default:
break
}
button.configuration = updatedConfiguration
}
self.configurationUpdateHandler = buttonStateHandler
```
버튼의 configuration를 업데이트 해주는 과정입니다. `button.configuration`
<br/>
<br/>
> [Add] #137 - UIButton Configuration 배경색 변경 코드 추가

- Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/grey50.colorset/Contents.json
- Terning-iOS/Terning-iOS/Resource/UIComponents/CustomOnboardingButton.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/View/OnboardingView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Welcome/View/WelcomeView.swift
close #144 
<br/>
UI만 수정되었습니다!
grey50 컬러 추가하였습니다!
<br/>
https://github.com/user-attachments/assets/444d26ef-de18-42a9-8023-ddd77817dfe9
<br/>
> [Fix] #144 -웰컴 & 온보딩 화면 UI 수정사항 반영했습니다.

- Terning-iOS/Terning-iOS/Resource/UIComponents/NewCustomAlertVC.swift
- Terning-iOS/Terning-iOS/Source/Data/Network/Service/Calendar/ScrapsService.swift
- Terning-iOS/Terning-iOS/Source/Data/Network/Service/Calendar/TNCalendarService.swift
- Terning-iOS/Terning-iOS/Source/Data/Repository/ScrapsRepository.swift
- Terning-iOS/Terning-iOS/Source/Data/Repository/TNCalendarRepository.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/JobListingCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
close #162 
<br/>
1. 알람창 로직 수정
저희가 서버에게 보낼때는 "red" 이렇게 컬러 네임으로 보내고요, 받을때는 "#ED4E54" 형태로 받습니다. 그래서 
`BehaviorRelay`를 두개로 나눴습니다.
```swift
let selectedColorNameRelay = BehaviorRelay<String>(value: "red") // 서버에 보낼때는 컬러 Name으로
let selectedColorHexRelay = BehaviorRelay<String>(value: "#ED4E54") // 서버에서 받을 때는 Hex로
```
이 부분이 통일 된다면 다른 곳은 수정될때 없었는데, 이 부분때문에 약간 관련된 로직들이 변경됐습니다.
2. 캘린더 스크랩 로직 수정
캘린더 Feature 의 수정, 삭제 로직이 변경되었습니다. 자세한건 PR Point를 참고해 주세요
3. 스크랩 Service에 스크랩 추가 서버 통신 구현
아래와 같이 addScrap을 추가 해줬습니다. 활용 하셔도 되고 어려우면 그냥 VC에 네트워크 통신 있는거 가져다 쓰면 됩니다.
```swift
protocol ScrapsRepositoryProtocol {
func addScrap(internshipAnnouncementId: Int, color: String) -> Observable<Void> // 추가 된 거 !
func patchScrap(internshipAnnouncementId: Int, color: String) -> Observable<Void>
func …
```
> [Refactor] #162 - 캘린더 스크랩 수정 및 삭제를 전면 수정하고, 알람창 일부를 변경 했습니다.

- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Source/Data/Network/Service/Calendar/ScrapsService.swift
- Terning-iOS/Terning-iOS/Source/Data/Repository/JobDetailRepository.swift
- Terning-iOS/Terning-iOS/Source/Data/Repository/TNCalendarRepository.swift
- Terning-iOS/Terning-iOS/Source/Domain/RepositoryInterface/JobDetailRepositoryInterface.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewModel/JobDetailViewModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift
close #177
<br/>
`ScrapService`가 제거돼서 오류 뜨는 문제 해결
<br/>
JobDetailRepositoryInterface 를 만들어주고,  `JobDetailRepository` 에서 구체적인 구현을 해주었습니다.
일단은 JobDetailRepository에는 스크렙 하는 메서드만 추가해뒀어요!
```swift
protocol JobDetailRepositoryInterface {
func addScrap(internshipAnnouncementId: Int, color: String) -> Observable<Void>
func patchScrap(internshipAnnouncementId: Int, color: String) -> Observable<Void>
func cancelScrap(internshipAnnouncementId: Int) -> Observable<Void>
}
```
JobDetailViewModel 를 보면 이렇게 되어 있는데, 사실 저 공고 서버 부분도 레포지토리에 넣어줘야합니다.
일단 그거는 조금 후로 미뤄두고 작업 합시다!
```swift
private let announcementsProvider = Providers.announcementsProvider
private let jobDetailRepository: JobDetailRepositoryInterface
```
<br/>
원래는 UseCase 모듈도 있어야 하는데, 너무 과하게 해버리면 여러분들 머리가 아프니까, 본격적으로 적용할때 한번 싹 알려드릴게요!
일단 …
> [Refactor] #177 - 공고상세, 검색결과 모듈 Repository 수정

- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/JobListingCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
close #179 
<br/>
1. 주간 캘린더, 리스트 캘린더에 그림자를 추가 하였습니다.
<br/>
원래는 `JobListingCell` 내부에 그림자를 넣어주려고 했는데, 저희 cell 왼쪽에 ColorMark 부분 때문에 수정사항이 제대로 반영이 안됐습니다. 
그래서 `Cell을 등록하는 부분`에 그림자를 넣어주는 방식으로 구현했습니다.
```swift
// 사용되는 부분들에 추가
cell.layer.applyShadow(color: .greyShadow, alpha: 1, y: 0, blur: 4)
```
<br/>
| 수정 전 | 수정 후 |
| - | - |
|  <img width="527" alt="스크린샷 2024-09-22 오후 1 10 22" src="https://github.com/user-attachments/assets/5a1d706e-52b8-4a3d-abcf-7023d6a29e32">  | <img width="527" alt="스크린샷 2024-09-22 오후 12 47 05" src="https://github.com/user-attachments/assets/c5050408-a0b6-47d7-b647-076a4f6abac9"> |
<br/>
> [Add] #179 - JobListingCell 에 그림자를 추가 하였습니다.

- Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/ScrapInfoHeaderCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
close #197 
<br/>
최종 QA를 반영했습니다. 반영한 사항은 아래와 같습니다.
<br/>
* 관심공고 -> 관심 공고 
| 변경 전 | 변경 후 |
| --- | --- |
| <img src="https://github.com/user-attachments/assets/1f621ede-6a92-45f1-9239-a129096c6d7c" width="300"/> | <img src="https://github.com/user-attachments/assets/05e5371b-fe9b-48c5-b5bf-687948d7cc3e" width="300"/> | 
* 스크랩 수정 성공 -> 스크랩 색상이 변경되었어요!
변경 전 | 변경 후 |
| --- | --- |
| <img src="https://github.com/user-attachments/assets/e0e7a0f1-f6db-40a3-b05a-bb9da74b02a1" width="300"/> | <img src="https://github.com/user-attachments/assets/f936e6c0-7616-4bc5-8c3e-18f5851a4b36" width="300"/> |
<br/>
> [Fix] #197 - 2차 QA를 반영했습니다. 

- Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift
- Terning-iOS/Terning-iOS/Resource/UIComponents/CustomNavigationBar.swift
- Terning-iOS/Terning-iOS/Source/Domain/Model/Home/UserProfileInfoModel.swift
- Terning-iOS/Terning-iOS/Source/Domain/Model/MyPage/MyPageCellModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/AccountOption/ViewController/AccountOptionViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/View/CalendarDateCellView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/InavailableFilterView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/MainInfoTableViewCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/MyPage/Cell/MyPageBasicViewCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/MyPage/ViewController/MyPageViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/MyPage/ViewModel/MyPageViewModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/View/OnboardingView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewController/ProfileViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/SearchCollectionViewHeaderCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/SortSetting/SortSettingViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Welcome/ViewController/WelcomeViewController.swift
close #199 
<br/>
<br/>
1. InavailableFilterView bind 함수 수정
한곳에만 쓰이는게 아니기 때문에 bind함수를 조정하여, QA에 해당하는 Search 부분만 변경 해주었습니다.
```swift
if title.count > 16 {
let titleRange = (fullText as NSString).range(of: finalTitle)
attributedString.addAttributes([
.font: UIFont.title4,
.foregroundColor: UIColor.terningMain
], range: titleRange)
let bodyRange = (fullText as NSString).range(of: "에\n해당하는 검색 결과가 없어요")
attributedString.addAttribute(.font, value: UIFont.body1, range: bodyRange)
} else {
// 글자 수가 16자 미만일 때
let titleRange = (fullText as NSString).range(of: finalTitle)
attributedString.addAttributes([
.font: UIFont.title4,
.foregroundColor: UIColor.terningMain
], range: titleRange)
let bodyRange = (fullText as NSString).range(of: "에 해당하는 검색 결과가 없어요")
attributedString.addAttribute(.font, value: …
```
> [Fix] #199 - 최종 QA 반영 하였습니다.

- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Info.plist
- Terning-iOS/Terning-iOS/Resource/Protocols/ProfileViewModelType.swift
- Terning-iOS/Terning-iOS/Source/Presentation/AccountOption/ViewController/AccountOptionViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewModel/ProfileViewModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/AdvertisementCollectionViewCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
close #202
<br/>
1. 프로필 닉네임 공백 허용
2. LoginViewController 네비게이션 제거
3. searchView -> rootView로 수정
4. 1.0.1 버전 변경
<br/>
> [Setting] #202 - v1.0.1 업데이트

- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Terning-iOS/Terning-iOS/Resource/Amplitude/AmplitudeEventType.swift
- Terning-iOS/Terning-iOS/Resource/Amplitude/AmplitudeManager.swift
- Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/UIView+.swift
- Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/ViewController+.swift
- Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift
- Terning-iOS/Terning-iOS/Source/Data/Network/Service/Login/LoginService.swift
- Terning-iOS/Terning-iOS/Source/Presentation/AccountOption/ViewController/AccountOptionViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/View/JobDetailView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/MyPage/Cell/MyPageAccountOptionViewCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/MyPage/ViewController/MyPageViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/ViewController/OnboardingPageViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewController/ProfileViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarController.swift
close #211 
<br/>
원하는 `ViewController` or `View` 부분에 사용하면 됩니다.
여러분 시험기간이라 제가 그냥 90% 이상 다 입력해 두었어요.
앰플리튜드를 처음 써봐서 모를 수 있는 여러분을 위해 짧게 설명하자면
간단한 코드 입력으로 유저들이 어떤 버튼을 누르고, 어떤 뷰에 오래 있고 여러 데이터를 가져올 수 있는 도구에요!
우리가 버튼을 막 누르면 아래처럼 기록이 된답니다!
코드 그냥 넘기지 말기
<br/>
1. 싱글톤으로 구현했고, VC 또는 View 에 track 메서드만 가져다 사용하면 됩니다.
```swift
public struct AmplitudeManager {
static public let shared = Amplitude(configuration: Configuration(apiKey: Config.AMPLITUDE_API_KEY))
private init() {}
}
```
익스 텐션에 구현 했어요!
```swift
extension UIViewController {
/**
- Description:
Amplitude 추적 메서드
*/
public func track(eventName: AmplitudeEventType, eventProperties: [String: Any]? = nil) {
AmplitudeManager.shared.track(eventType: eventName, eventProperties: eventProperties)
}
public func trackScreenDuration(eventName: …
```
> [Feat] #211 - Amplitude 구현 및 세팅

- README.md
- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Info.plist
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/View/TNCalendarView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/UnavailableFilterView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/AdvertisementCollectionViewCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/View/SearchResultView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
close #217 
<br/>
1. 네이밍 부분에서 일부 오타 및 컨벤션 수정했습니다.
2. 빌드 버전 1.0.2로 올려 앱스토어 배포 완료했습니다.
3. 저희 README.md 도 일부 수정했습니다.
<br/>
<br/>
> [Setting] #217 - v1.0.2 버전 배포 했습니다.

- Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/SearchTargetType.swift
- Terning-iOS/Terning-iOS/Source/Domain/Model/Search/AdvertisementsModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewModel/TNCalendarViewModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/AdvertisementCollectionViewCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/View/SearchView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewModel/SearchViewModel.swift
close #222
<br/>
1. 배너 API 연결 했습니다.
<br/>
API 명세를 보면 banner 배열에 원하는 데이터 타입이 들어있기 때문에 아래처럼 구조체를 만들 수밖에 없었습니다.
```swift
struct AdvertisementModel: Codable {
let banners: [BannerModel]
}
struct BannerModel: Codable {
let imageUrl: String
let link: String
}
```
```swift
private func fetchAdveriseData() -> Observable<[BannerModel]> { ... }
```
<br/>
<br/>
> [Feat] #222 - 배너 API 호출로 변경 했습니다.

- README.md
- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Info.plist
- Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewController/ProfileViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
close #224 
<br/>
1. track 코드를 배너와, 유저가 처음 시작하는 버튼에 심었습니다.
2. v1.0.4 버전을 배포 했습니다.
<br/>
> [Setting] #224 - v1.0.4 버전 배포, 일부 Amplitude 추적 Event 추가 하였습니다.

- Terning-iOS/Terning-iOS/Resource/UIComponents/CustomDatePicker.swift
- Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift
- Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringView/ViewController/FilteringViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/JobFiltering/Cell/JobCategoryCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/PlanFiltering/ViewController/PlanFilteringViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/View/OnboardingView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Welcome/View/WelcomeView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Welcome/ViewController/WelcomeViewController.swift
close #233 
<br/>
 (기존 7줄 -> 5줄)
+ 추가)
--> 이거 보니깐 안했더라고요,.,.
<br/>
https://github.com/user-attachments/assets/9ff40b26-045b-4626-948f-acc703d4a290
https://github.com/user-attachments/assets/84104314-d77e-40f9-a3c0-7c74428ee191
<br/>
> [Fix] #233 - 온보딩, 웰컴뷰 디자인 수정했습니다.

- Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/JobCardCell.swift
close #238 
<br/>
<br/>
JobCardCell의 bind 함수만 수정했습니다!
```swift
func bind(model: AnnouncementModel, indexPath: IndexPath) {
if model.dDay == "지원마감" {
self.daysRemaining.textColor = .grey300
self.jobLabel.textColor = .grey300
self.periodTitle.textColor = .grey300
self.period.textColor = .grey300
self.jobCardCoverImage.layer.opacity = 0.5
} else {
self.daysRemaining.textColor = .terningMain
self.jobLabel.textColor = .black
self.periodTitle.textColor = .grey400
self.period.textColor = .terningMain
self.jobCardCoverImage.layer.opacity = 1.0
}
self.internshipAnnouncementId = model.internshipAnnouncementId
self.jobCardCoverImage.setImage(with: model.companyImage, placeholder: "placeholder_image")
self.daysRemaining.text = model.dDay
self.jobLabel.text = model.title
self.period.text = …
```
> [Feat] #238 - JobCardCell 마감공고 UI 디자인 변경

- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Resource/UIComponents/EmptyView.swift
- Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift
- Terning-iOS/Terning-iOS/Source/Data/Network/Service/Home/HomeService.swift
- Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/HomeTargetType.swift
- Terning-iOS/Terning-iOS/Source/Data/Repository/HomeRepository.swift
- Terning-iOS/Terning-iOS/Source/Data/Repository/ScrapRepository.swift
- Terning-iOS/Terning-iOS/Source/Domain/UseCase/HomeUseCase.swift
- Terning-iOS/Terning-iOS/Source/Domain/UseCase/ScrapUseCase.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/View/TNCalendarView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringView/ViewController/FilteringViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/CheckDeadlineCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/Cell/ClosingJobAnnouncementCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/Cell/StickyHeaderCell.swift
- Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/MainSortButton.swift
- Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/NewHomeView.swift
- Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/NewHomeViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/ViewModel/HomeViewModel.swift
- Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarItem.swift
close #235 
<br/>
1. 홈 화면 전면 수정
2. 주간 캘린더 swipe 바 추가
<br/>
복잡한 로직이 많은데, 단기간에 구현을 하려다 보니 아키텍처에 대한 생각을 많이 못했습니다.
일반적인 CleanArchitectrue 기반으로 구현 했는데 아직 제대로 나누진 못했습니다.
Presentation(MVVM) -> Domain <- Data
형식으로 구현 했다고 생각 하면 됩니다.
크게 바뀐점은 처음 화면에 들어왔을때의 서버 호출인데요
약 20번
과거 민성이가 짠 코드와 비교 하면 약 80% 줄인 것을 볼 수 있습니다.
`collectionView.rx.contentOffset` 를 활용해서 구현 했습니다.
---
공고 정렬하면 정렬된 기준이 홈 화면에 정렬 버튼 text 가 수정되어야 하는데 로직에 문제가 생겨서.. 추후에 수정할 계획입니다.
<br/>
<br/>
NewHomeViewController에서 시간이 부족해서 하나의 API는 그냥 ViewController에서 받게 했는데요, 이 부분은 리팩토링을 통해 개선할 계획 입니다.
그리고 기간 필터 뷰나, 몇개의 Cell들은 기존 민성이가 만든걸 재사용 했는데요 .. 그러다 보면 Delegate패턴들이 많아서 코드의 복잡도가 높아지게 됩니다 ..
이 부분도 RxSwfit를 통해 리팩토링을 하여 최대한 줄일 계획 입니다.
<br/>
> [Refactor] #235 - 홈 화면 전면 수정 했습니다.

- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Info.plist
- Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringView/ViewController/FilteringViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/NewHomeViewController.swift
- Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarItem.swift
close #243
<br/>
1. 새로운 홈에 `filterInfos` 변수를 추가하여, FilterViewController의 생성자에 넣어주었습니다.
2. 버전 1.1.0 로 올렸습니다.
<br/>
1. NewHomeViewController에 아래 변수를 추가했습니다.
```swift
var filterInfos: UserFilteringInfoModel = UserFilteringInfoModel(
grade: nil, // 기본값 설정
workingPeriod: nil, // 기본값 설정
startYear: nil, // 기본값 설정
startMonth: nil, // 기본값 설정
jobType: nil
)
```
추가로 필터링을 연결하는 서버도 연결 해주었습니다.
<br/>
<br/>
> [Feat] #243 - 홈화면과 필터링을 연결 합니다.

- README.md
- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Info.plist
- Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/UITextView+.swift
- Terning-iOS/Terning-iOS/Resource/Utils/TextViewFactory.swift
- Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/DetailInfoTableViewCell.swift
close #254
<br/>
- 공고 상세에서 내용에 해당하는 부분을 UILabel에서 UITextView로 수정 했습니다
- 앱스토어에 1.1.2 버전 업데이트 했습니다.
<br/>
그에 따라 UITextViewFactory도 재사용 될 수 있는 가능성이 있어 하나 만들었습니다.
```swift
struct TextViewFactory {
/// - Parameters:
///   - text: TextView에 보여줄 텍스트
///   - font: 텍스트의 폰트
///   - backgroundColor: TextView의 배경색
///   - textColor: text 색상
///   - textAlignment: text 정렬
///   - lineSpacing: 행간 (default = 1.3 (130%))
///   - characterSpacing: 자간 (default = -0.5 (-0.005))
///
static func build(
text: String? = "",
font: UIFont,
backgroundColor: UIColor = .clear,
textColor: UIColor = .terningBlack,
textAlignment: NSTextAlignment = .center,
lineSpacing: CGFloat = 1.3,
characterSpacing: CGFloat = -0.005
) -> UITextView {
let textView = UITextView()
textView.text = text
textView.font = font …
```
> [Fix] #254 - 공고 상세에서 복사 붙여넣기 기능이 되게 수정 했습니다. | v1.1.2 버전 업데이트

- Terning-iOS/Terning-iOS/Presentation/FilteringSetting/JobFiltering/Cell/JobCategoryCell.swift
grey200 -> grey150
close #267
<br/>
- 직무 카테고리 버튼 테두리 색을 변경 하였습니다.
<br/>
<br/>
- 티 좀 나나요? ㅋ
<br/>
> [Fix] #267 - 직무 카테고리 테두리 Color를 변경 했습니다.

- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Resource/UIComponents/UpdateAlertViewController.swift
close #281 
<br/>
- 업데이트 다이얼로그 UI를 구현했습니다.
이번에는 기존과 달리 Reactive Extension 으로 구현 했습니다. 사용법은 아래 자세하게 적어 두겠습니다.
파일은 UpdateAlertViewController.swift 참고
<br/>
생성자로는 `타입`, `title`, `discription` 을 넣어주면 됩니다.
```swift
let alert = UpdateAlertViewController(
updateViewType: .force,
title: "강제업데이트",
discription: "강제업데이트를 \n해야합니다"
)
```
`타입(updateViewType)`은 2가지가 존재합니다.
| normal | force |
|:-----:|:-------:|
| ![Simulator Screenshot - iPhone 15 Pro - 2025-03-18 at 11 13 34](https://github.com/user-attachments/assets/c43a81d5-2f78-4dcd-a611-e80c7cfaeb30) | ![Simulator Screenshot - iPhone 15 Pro - 2025-03-18 at 11 16 13](https://github.com/user-attachments/assets/2759108d-9947-4c23-b68f-51c942c7af91) |
rx로 접근하여 구독을 하면 버튼의 이벤트 처리를 외부에서 할 수 있습니다.
외부에서는 앱스토어 이동 처리, 닫는 처리만 해주면 됩니다.
```swift
let vc = …
```
> [Feat] #281 - 강제업데이트 다이얼로그 UI 구현 했습니다.

- Terning-iOS/Terning-iOS/Presentation/Home/Cell/StickyHeaderCell.swift
- Terning-iOS/Terning-iOS/Presentation/Home/View/MainFilterButton.swift
- Terning-iOS/Terning-iOS/Presentation/Home/View/MainSortButton.swift
close #283 
<br/>
- 홈 화면에 있는 정렬 버튼 pressed 기능 추가
- 홈 화면에 있는 필터링 버튼 pressed 기능 추가
<br/>
실제로 정렬 버튼은 UIView로 초기에 구현 했는데, 다시 보니 Button으로 구현하는게 좋아 타입을 변경 해주었습니다.
```swift
final class MainSortButton: UIButton { ... }
```
<br/>
<br/>
> [Fix] #283 - 홈 버튼 Pressed 상태 추가

- README.md
- Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
- Terning-iOS/Terning-iOS/Presentation/MyPage/ViewModel/MyPageViewModel.swift
close #297
<br/>
1. myPage에서 푸시 알림 on인지 off인지 알려주는 값도 넘겨줘서 일부 수정 했습니다.
2. 1.3.1 버전으로 앱스토어 배포 했습니다.
<br/>
<br/>
<br/>
> [Fix] #297 - 푸시알림 온오프 기능 일부 수정 및 v1.3.1 배포 했습니다.
